name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: git config --global advice.addIgnoredFile false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Install Gem dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor
          sudo apt-get install -y graphviz
          sudo apt-get install -y plantuml

      - name: Generate PlantUML Diagram
        run: |
          for file in 02_Software_Arch/*.puml; do
            plantuml -tpng $file -o ../docs/
          done
      - name: Convert AsciiDoc to PDF and HTML
        run: |
          asciidoctor -r asciidoctor-pdf -r asciidoctor-diagram -b pdf 02_Software_Arch/software_arch.adoc -o docs/software_arch.pdf
          asciidoctor -o docs/software_arch.html 02_Software_Arch/software_arch.adoc
          asciidoctor -r asciidoctor-pdf -r asciidoctor-diagram -b pdf Research_Benchmarking/blip2.adoc -o docs/blip2_benchmarking.pdf
          asciidoctor -o docs/blip2_benchmarking.html Research_Benchmarking/blip2.adoc

      - name: Commit and Push Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/*.pdf
          git add docs/*.html
          git add docs/*.png
          git commit -m "Benchmarking documentation."
          git -c http.extraHeader="AUTHORIZATION: basic $(echo -n x-access-token:${GITHUB_TOKEN} | base64)" push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}